USE COMPANY;

CREATE TABLE DEPARTMENT
(DNO VARCHAR(20) PRIMARY KEY,
DNAME VARCHAR(20), MGRSTARTDATE
DATE,MGRSSN VARCHAR(20)); 

CREATE TABLE EMPLOYEE
(SSN VARCHAR(20) PRIMARY KEY,
FNAME VARCHAR(20),
LNAME VARCHAR(20),
ADDRESS VARCHAR(20),
SEX CHAR(1), SALARY
INTEGER,
SUPERSSN VARCHAR(20),
FOREIGN KEY(SUPERSSN) REFERENCES EMPLOYEE(SSN),
DNO VARCHAR(20),
FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO));

ALTER TABLE DEPARTMENT ADD FOREIGN KEY(MGRSSN) REFERENCES EMPLOYEE (SSN);

CREATE TABLE DLOCATION 
(DLOC VARCHAR(20), 
DNO VARCHAR(20),
FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO), 
PRIMARY KEY(DNO, DLOC));

CREATE TABLE PROJECT(PNO 
INTEGER PRIMARY KEY, PNAME 
VARCHAR(20), 
PLOCATION VARCHAR(20), 
DNO VARCHAR(20),
FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO));

CREATE TABLE WORKS_ON 
(HOURS NUMERIC(2), 
SSN VARCHAR(20),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN), 
PNO INTEGER,
FOREIGN KEY(PNO) REFERENCES PROJECT(PNO), 
PRIMARY KEY(SSN, PNO));